channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.9
  - pip=21.0
  - cudatoolkit=10.2
  - pytorch=1.8
  - torchvision=0.9.1
  - xarray=0.17
  - scikit-learn=0.24.2
  - numpy=1.20.2
  - netcdf4=1.5.6
  - pip:
    - pytorch-lightning==1.3
    - einops==0.3.0