channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
  - pyviz
dependencies:
  - jupyterlab
  - python=3.9
  - pip=21.1
  - scikit-learn=0.24.2
  - cartopy=0.19.0
  - cartopy_offlinedata=0.2.4
  - tabulate=0.8.9
  - xrft=0.4.1
  - numpy_groupies=0.9.13
  - pytorch-lightning=1.6.2
  - pip:
    - xarray[complete]==0.21
    - holoviews[recommended]
    - sparse
    - GitPython
    - einops
    - hydra-submitit-launcher
    - opencv-python==4.5.2.52
    - hydra-core
    - kornia
    - pyepsg
